config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  devise_for :users
  root 'posts#index'
  resources :posts, only: %w[index new show create] do
    resources :comments, only: :create
    resources :likes, only: %i[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :restrict_with_error

  validates :name, uniqueness: true, presence: true, length: { minimum: 3, maximum: 40 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: 'posts'
  has_many :comments, dependent: :destroy, class_name: 'PostComment', inverse_of: 'post'
  has_many :likes, dependent: :destroy, class_name: 'PostLike', inverse_of: 'post'

  validates :title, presence: true, length: { minimum: 5, maximum: 255 }
  validates :body, presence: true, length: { minimum: 200, maximum: 4000 }

  def like_by_user(current_user)
    return nil if current_user.nil?

    likes.find_by({ user_id: current_user.id })
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  has_ancestry

  belongs_to :post, inverse_of: 'comments'
  belongs_to :user, inverse_of: 'comments'

  validates :content, length: { minimum: 5, maximum: 400 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: 'likes_count'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy, class_name: 'PostComment'
  has_many :likes, dependent: :destroy, class_name: 'PostLike'

  validates :email, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :error
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_post, only: :create

  def create
    @root_comment = @post.comments.build(comment_params)
    @root_comment.user = current_user

    respond_to do |format|
      if @root_comment.save
        format.html { redirect_to post_url(@post), notice: I18n.t('comments.create.success') }
      else
        format.html { redirect_to post_url(@post), error: @root_comment.errors.full_messages.join(".\n") }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[create]

  def create
    @like = @post.likes.new({ user_id: current_user.id })

    respond_to do |format|
      if @like.save
        format.html { redirect_to post_url(@post) }
      else
        format.html { redirect_to post_url(@post), notice: @like.errors.full_messages }
      end
    end
  end

  def destroy
    @like = current_user.likes.find_by(id: params[:id])
    return redirect_to post_url(params[:post_id]) if @like.nil?

    respond_to do |format|
      if @like.destroy
        format.html { redirect_to post_url(params[:post_id]) }
      else
        format.html { redirect_to post_url(params[:post_id]), notice: @like.errors.full_messages }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.includes(:creator).all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).arrange(order: { created_at: :desc })
    @user_like = @post.like_by_user(current_user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: I18n.t('simple_form.post.create.success') }
      else
        flash.now[:error] = I18n.t('simple_form.post.create.fail')
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id, :user_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_card.html.slim
. id="comment-#{comment.id}" class ="card mt-2 rounded-0"
  .card-header.border-0
    = link_to '#', post_path(comment.post, anchor: "comment-#{comment.id}"), class: 'me-2'
    span.me-2 = comment.user.email
    span.fs-6.text-muted = comment.created_at.strftime '%d %b., %H:%M'
  .card-body.border-0
    = comment.content
  .card-footer.border-0
    - if user_signed_in?
      a.fs-6.text-decoration-underline.text-lowercase [
        type='button' aria_expanded="false"
        aria_controls="#response_comment-#{comment.id}"
        data-bs-target="#response_comment-#{comment.id}"
        data-bs-toggle="collapse"
        href="#"
      ]
        = t('simple_form.comment.reply')
      . id="response_comment-#{comment.id}" class = "ms-2 collapse"
        = render partial: 'comments/form', locals: { parent: comment }
  - if local_assigns.key? :children
    .ms-4
      - children.each do |comment, children|
        = render partial: 'comments/card', locals: { comment:, children: }

app/views/comments/_form.html.slim
= simple_form_for @post.comments.new, url: post_comments_path(@post) do |f|
  = f.input :content, label: false
  - if local_assigns.key? :parent
    = f.input :parent_id, as: :hidden, input_html: { value: parent.id }
  = f.button :submit, t('simple_form.comment.comment'), class: 'btn-primary mt-2'

app/views/layouts/application.html.slim
<!DOCTYPE html>
html lang='en'
  head
    meta charset='UTF-8'/
    meta name='viewport' content='width=device-width, initial-scale=1.0'/
    title = t('shared.title')

    =csrf_meta_tags
    =csp_meta_tag

    =stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    =javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body.d-flex.flex-column.h-100
    .container.mb-2
      .d-flex.flex-wrap.align-items-center.py-2.border-bottom
        = link_to image_tag('logo.jpg', width: '30', alt: 'logo.jpg'), root_path, class: 'navbar navbar-expand-md navbar-light me-auto'
        .ul.nav
          - if user_signed_in?
            li.nav-item
              p.nav-link.disabled = current_user.email
            li.nav-item = link_to t('shared.new_post'), new_post_path, class: 'nav-link link-dark'
            li.nav-item = link_to t('shared.logout'), destroy_user_session_path, data: { 'turbo-method': :delete }, class: 'nav-link link-dark'
          - else
            li.nav-item = link_to t('shared.sign_in'), new_user_session_path, class: 'nav-link link-dark'
            li.nav-item = link_to t('shared.sign_up'), new_user_registration_path, class: 'nav-link link-dark'

    .container.mb-4
      - if flash.any?
        - flash.each do |type, msg|
          - case type
          - when 'alert'
            .alert.alert-info
              = msg
          - when 'notice'
            .alert.alert-success
              = msg
          - when 'error'
            .alert.alert-danger
              = msg
          - else
            p = "Unhandled notice: #{type} - #{msg}"
      = yield

app/views/posts/_card.html.slim
.col-md-12
  .card.mb-3
    .card-body
      h5.card-title
        = link_to post.title, post_path(post), { class: 'link-dark text-decoration-none' }
      .card-text.mb-2 = post.body.truncate(300, omission: '...')
      .text-right.small.text-muted.mt-auto
        span.me-2 = "#{t('post.liked')}: #{post.likes.size}"
        span.me-2 = time_ago_in_words post.created_at
        span = post.creator.email

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.input :title, hint: t('simple_form.hint.length', min: 5, max: 255)
  = f.association :category, required: true
  = f.input :body, as: 'text', hint: t('simple_form.hint.length', min: 200, max: 4000), input_html: { rows: 10 }
  = f.button :submit, t('simple_form.post.publish'), class: 'btn-primary mt-3'

app/views/posts/_post-card.html.slim
.col-md-12
  .card.mb-3
    .card-body
      h5.card-title
        = link_to post.title, post_path(post), { class: 'link-dark text-decoration-none' }
      .card-text.mb-2 = post.body.truncate(300, omission: '...')

app/views/posts/_post.html.slim
article.col-12
  h1.mb-4.mb-l-5 = post.title
  p
  p = post.body
  p
  .d-flex.justify-content-between.mt-5
      #post-section
        span.me-2 = post.creator.email
        span = time_ago_in_words post.created_at
      #likes-section
        span.me-2 = post.likes.size
        - if user_signed_in?
          - if user_like.nil?
            = link_to post_likes_path(post), data: { 'turbo-method': :post }, class: 'link-dark' do
              i.bi.bi-hand-thumbs-up
          - else
            = link_to post_like_path(post, user_like), data: { 'turbo-method': :delete }, class: 'link-dark' do
              i.bi.bi-hand-thumbs-up-fill
        - else
          i.bi.bi-hand-thumbs-up

app/views/posts/index.html.slim
h1 = t('post.index.title')
.row
  - @posts.each do |post|
    = render 'card', post:

app/views/posts/new.html.slim
h1 = t('post.new.title')
= render 'form', post: @post

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item = link_to t('post.show.all_posts_link'), posts_path
  li.breadcrumb-item.active = @post.category.name
.row.justify-content-center.mt-4
= render partial: 'post', locals: { post: @post, user_like: @user_like }

#comments-section.lead.mt-3
  span = t('post.show.comments')
  - if user_signed_in?
    = render 'comments/form'
  - @comments.each do |comment, children|
    = render partial: 'comments/card', locals: { comment:, children: }